name:           bitcoin-spv-wallet
version:        '0.1.0.0'
category:       Bitcoin Finance Network
author:         Rune K. Svendsen
maintainer:     runesvend@gmail.com
copyright:      2017 Rune K. Svendsen
license:        OtherLicense
license-file:   LICENSE
github:         runeksvendsen/bitcoin-spv-wallet

default-extensions:
- OverloadedStrings
- ScopedTypeVariables

dependencies:
- base >=4.7 && <5
- haskoin-core
- haskoin-node
- haskoin-wallet
- aeson
- zeromq4-haskell
- mtl
- text
- string-conversions
- persistent-sqlite
- unordered-containers
- monad-logger
- resourcet
- retry
- exceptions

library:
  source-dirs: src
  exposed-modules:
  - Bitcoin.SPV.Wallet
